### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by miccoli** [jthiem/nnresample#9] opened 2018-09-29 16:41 UTC
`pip install nnresample` fails if scipy is not already installed.

```
$ pip install nnresample
Collecting nnresample
  Using cached https://files.pythonhosted.org/packages/7d/8b/b985e73ce4422b150f281fb6a843339cc92a3c9ba4e175113586de0f31b2/nnresample-0.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rx/47f7x4br8xj_jj00r6bcm6y80000gq/T/pip-install-9lm1mxr2/nnresample/setup.py", line 2, in <module>
        import nnresample
      File "/private/var/folders/rx/47f7x4br8xj_jj00r6bcm6y80000gq/T/pip-install-9lm1mxr2/nnresample/nnresample/__init__.py", line 3, in <module>
        from .nnresample import resample, compute_filt
      File "/private/var/folders/rx/47f7x4br8xj_jj00r6bcm6y80000gq/T/pip-install-9lm1mxr2/nnresample/nnresample/nnresample.py", line 2, in <module>
        import scipy.signal as sig
    ModuleNotFoundError: No module named 'scipy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/rx/47f7x4br8xj_jj00r6bcm6y80000gq/T/pip-install-9lm1mxr2/nnresample/
```

The problem is clearly in <https://github.com/jthiem/nnresample/blob/b1f4c5930bb5c09f8993d9ab904dffb6eeabddc5/setup.py#L2>

In fact you cannot import nnresample (which in turn imports scipy) during the installation process itself, because there is no guarantee that scipy is already installed.

There is a lot of discussion on how to include version info into `setup.py`, but simply importing the package itself is bad practice.

If I may give you a suggestion, just delete `setup.py` and try [flit](https://flit.readthedocs.io/en/latest/), which should work out of the box. I can provide a pull request with the necessary setup, if you want.

**Comment by jthiem** [comment] 2018-10-02 18:27
Hi Stefano, thanks for the bug report.  I managed to reproduce the problem (which I had never seen before since I pretty much always have scipy installed) and looking at the code, it's obvious.

flit looks nice, but I think the best way to fix the problem right now is to remove the version from `__init__.py` and move it into setup.py, thus removing the need to import the package from setup.py.

I've put the changes into the dev branch, and will merge it later.  Maybe I'll add some tests.

**Comment by miccoli** [comment] 2018-10-02 20:09
I don't think your fix is good: it is a common convention to have the version number available in `<package>.__version__` but in 6ac6d59c5b521cbd935213630bcb137860b16251 there is no `nnresample.__version__`:

<https://github.com/jthiem/nnresample/blob/6ac6d59c5b521cbd935213630bcb137860b16251/nnresample/__init__.py#L1-L2>

See <https://packaging.python.org/guides/single-sourcing-package-version/> for reference on common strategies for managing the version number. But again, for your usage case, flit seems to me the best approach: simple, easy to maintain, supports wheels.

BTW, thank you for your package, which I found very useful.

**Comment by jthiem** [comment] 2018-10-06 19:56
You're right, my fix removes the `__version __` attribute.  I need a better fix.

Thank you for the link, that is the best overview of the options I have seen so far, and I had been looking for  exactly that kind of summary. I note that my method is listed there, with the exact problem being described.

I would still prefer to use a method that does not involve additional packages, but if you want to send me a pull request which uses flit, I'll have a look at it.  Frankly, this is an issue for which there should be One True Way (TM) of doing it, and IMHO setuptools should be the thing doing it!

Footnote. It seem a silly problem anyways, since pip is basically incapable of building scipy by the uninitiated anyways.  It requires (dev-packages of) blas and lapack, not to mention a *FORTRAN* compiler to be present.

**Comment by miccoli** [comment] 2018-10-06 21:40
Both setuptools and flit do no belong to the python standard library, so both are "additional packages", as well as pip.

pip supports [wheels](https://pythonwheels.com), so nowadays it is very uncommon to build a package from source, but more commonly a binary wheel is downloaded and installed. When using [virtual environments](
https://docs.python.org/3/tutorial/venv.html#virtual-environments-and-packages) it is very common to start from a "clean" environment, and install all desired packages from scratch.

Let me show this by two  examples:
<details>
<summary>clean install of nnresample</summary>

```
$ python -m venv ./test
$ . ./test/bin/activate
(test) $ pip list
Package    Version
---------- -------
pip        10.0.1 
setuptools 39.0.1 
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test) $ pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 6.4MB/s 
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-18.1
(test) $ pip install scipy
Collecting scipy
  Using cached https://files.pythonhosted.org/packages/4c/4a/440cc9703938bbc86636ff6b9e17810f3d0f06e9b41891c5433dc4cd9091/scipy-1.1.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting numpy>=1.8.2 (from scipy)
  Using cached https://files.pythonhosted.org/packages/f9/64/f47c172c2d2ee8907b5918ff7af7e52207f6bf4a57983e4474fcda728112/numpy-1.15.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: numpy, scipy
Successfully installed numpy-1.15.2 scipy-1.1.0
(test) $ pip install nnresample
Collecting nnresample
  Using cached https://files.pythonhosted.org/packages/7d/8b/b985e73ce4422b150f281fb6a843339cc92a3c9ba4e175113586de0f31b2/nnresample-0.2.3.tar.gz
Requirement already satisfied: scipy<2.0.0,>=0.18.0 in ./test/lib/python3.7/site-packages (from nnresample) (1.1.0)
Requirement already satisfied: numpy>=1.8.2 in ./test/lib/python3.7/site-packages (from scipy<2.0.0,>=0.18.0->nnresample) (1.15.2)
Installing collected packages: nnresample
  Running setup.py install for nnresample ... done
Successfully installed nnresample-0.2.3
(test) $ pip list
Package    Version
---------- -------
nnresample 0.2.3  
numpy      1.15.2 
pip        18.1   
scipy      1.1.0  
setuptools 39.0.1 
```

</details>

<details>
<summary>failed nnresample install </summary>

```
$ python -m venv ./test-2
$ . ./test-2/bin/activate
(test-2) $ pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-18.1
(test-2) $ pip list
Package    Version
---------- -------
pip        18.1   
setuptools 39.0.1 
(test-2) $ pip install nnresample
Collecting nnresample
  Using cached https://files.pythonhosted.org/packages/7d/8b/b985e73ce4422b150f281fb6a843339cc92a3c9ba4e175113586de0f31b2/nnresample-0.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rx/47f7x4br8xj_jj00r6bcm6y80000gq/T/pip-install-z87orp61/nnresample/setup.py", line 2, in <module>
        import nnresample
      File "/private/var/folders/rx/47f7x4br8xj_jj00r6bcm6y80000gq/T/pip-install-z87orp61/nnresample/nnresample/__init__.py", line 3, in <module>
        from .nnresample import resample, compute_filt
      File "/private/var/folders/rx/47f7x4br8xj_jj00r6bcm6y80000gq/T/pip-install-z87orp61/nnresample/nnresample/nnresample.py", line 2, in <module>
        import scipy.signal as sig
    ModuleNotFoundError: No module named 'scipy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/rx/47f7x4br8xj_jj00r6bcm6y80000gq/T/pip-install-z87orp61/nnresample/
```

</details>


Please note also that flit is only needed by the package maintainer, it is not a run-time dependence.

I will shortly provide a PR with the proper setup.

**Comment by jthiem** [comment] 2018-10-17 21:53
Thanks for your pull request, flit works as advertised, but I think I prefer the "self-contained" approach as described by point 1 in the "single sourcing package version" link you posted.  Less things to install into a fresh development environment.  More transparent what's going on.

I updated the dev branch.

The problems I had installing scipy using pip were on arm, btw... I guess those wheels are not there yet.

**Comment by miccoli** [comment] 2018-10-18 07:19
No problem, please feel free to close my pull request. Just a side note about the "self contained" approach.

Current best practice is to upload on pypi also a wheel, this means that the tool stack with setuptools is
- setuptools
- [wheel](https://pypi.org/project/wheel/) 
- [twine](https://pypi.org/project/twine/) (`python setup.py upload` is deprecated)

On the contrary the tool stack with flit is
- flit

and that's it. Somehow for simpler packages I find the `pyptoject.toml` (defined as standard in [PEP 518](https://www.python.org/dev/peps/pep-0518/)) easier to maintain than `setup.cfg`. But this is just my personal feeling, and It is pointless to argue about preferences.

Thanks again for your package.

**Comment by jthiem** [comment] 2018-11-05 21:38
Should be fixed now.  Thanks for the contribution!

**Closed as completed by jthiem** 2018-11-05 21:38 UTC
